version: '2.0'

# networks
networks:
  default:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      default:
    restart: always
    volumes:
      - /opt/appdata/guacamole/drive:/drive:rw
      - /opt/appdata/guacamole/record:/record:rw
  # postgres
  postgres:
    container_name: postgres_db
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: SomePassword
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      default:
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - /tank/appdata/guacamole/data:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: SomePassword
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      default:
    ports:
      - 8080:8080/tcp
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:guacamole.yourdomain.com,guac.yourdomain.com; AddPrefix: /guacamole"
      traefik.port: "8080"
    restart: always
